name: IGInfos
author: ZeSowK
version: 0.3
main: fr.zsk.iginfo.IGInfos
commands:
  serverinfos:
    description: Obtenir des informations serveur
  adminsrinfos:
    description: Obtenir des informations serveur(Mode Administrateur)